#include<iostream>
using namespace std;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main(){
  int lasttwo[2] = {1,2};
  int sum = 2;
  int current = 0;
  
  while (current < 4000000){
    current = 0;
    for (int i=0; i<2; i++){current += lasttwo[i];}
    lasttwo[0] = lasttwo[1];
    lasttwo[1] = current;

    if  (current%2==0){sum+=current;}
  }
  cout << sum << endl;
}
